/**
 * Core TypeScript type definitions for the Cortex AI Workspace.
 *
 * These interfaces map to the Supabase database tables and API response shapes.
 */

/**
 * Represents an uploaded document stored in Supabase.
 *
 * Maps to the `documents` table with columns for user ownership,
 * file metadata, and processing status.
 */
export interface Document {
  /** Unique document identifier (UUID). */
  id: string
  /** ID of the user who uploaded the document. */
  user_id: string
  /** Display title derived from the file name. */
  title: string
  /** Supabase Storage URL of the raw file. */
  file_url: string
  /** MIME type or file extension of the uploaded file. */
  file_type: string
  /** ID of the project this document belongs to, or `null` if unassigned. */
  project_id: string | null
  /** Processing status: `"pending"`, `"processing"`, `"ready"`, or `"failed"`. */
  status: string
  /** ISO 8601 timestamp of when the document was created. */
  created_at: string
}

/**
 * Represents a user-created project for organizing documents.
 *
 * Maps to the `projects` table.
 */
export interface Project {
  /** Unique project identifier (UUID). */
  id: string
  /** ID of the project owner. */
  user_id: string
  /** Human-readable project name. */
  name: string
  /** Optional description of the project's purpose. */
  description: string
  /** ISO 8601 timestamp of when the project was created. */
  created_at: string
}

/**
 * A single search result reference pointing to a chunk within a document.
 */
export interface SearchReference {
  /** Title of the document containing this chunk. */
  document_title: string
  /** UUID of the source document. */
  document_id: string
  /** Full text content of the matched chunk. */
  content: string
  /** Truncated excerpt of the chunk for display. */
  excerpt: string
  /** Similarity score from the vector search (0.0–1.0). */
  score: number
  /** Human-readable relevance label derived from the score. */
  relevance: "high" | "medium" | "low"
}

/**
 * Complete search response returned by the `/api/search` endpoint.
 *
 * Contains a summary, key points extracted from results, and per-chunk references.
 */
export interface SearchResponse {
  /** The original search query. */
  query: string
  /** AI-generated or extractive summary of the search results. */
  summary: string
  /** Bullet-point key topics extracted from the results. */
  key_points: string[]
  /** Ranked list of chunk references matching the query. */
  references: SearchReference[]
  /** Total number of chunks retrieved (may differ from references length). */
  total_chunks?: number
  /** Whether the summary was generated by AI (true) or extractive (false). */
  ai_generated: boolean
  /** Whether documents are still being processed (results may be incomplete). */
  processing_documents?: boolean
}

/**
 * A saved entry in the user's search history.
 *
 * Maps to the `search_history` table.
 */
export interface SearchHistoryItem {
  /** Unique history entry identifier (UUID). */
  id: string
  /** The search query that was executed. */
  query: string
  /** Optional short summary of the results. */
  result_summary: string | null
  /** Optional count of source documents that matched. */
  source_count: number | null
  /** ISO 8601 timestamp of when the search was performed. */
  created_at: string
  /** Whether the user has bookmarked/saved this search. */
  saved?: boolean
}
